###Create employee
POST https://employee-backend-xxcu.onrender.com/employee-api/employee
Content-Type: application/json

{
    "name":"Harish",
    "email":"harish@gmail.com",
    "mobile":"8888888",
    "designation":"developer",
    "companyName":"TCS"
}

###Read all employees
GET https://employee-backend-xxcu.onrender.com/employee-api/employee

###edit employee
PUT https://employee-backend-xxcu.onrender.com/employee-api/employee/69caa833c313c15eadc49d51
Content-Type: application/json

{
   "name":"Harish",
    "email":"harishraj@mail.com",
    "mobile":9999999,
    "designation":"developer",
    "companyName":"cts"
}

###delete employee
DELETE https://employee-backend-xxcu.onrender.com/employee-api/employee/69caa833c313c15eadc49d51
