### Register User
POST https://atp-24eg112d06.onrender.com/auth/users
Content-Type: application/json

{
    "firstName":"user1",
    "lastName":"",
    "email":"user1@gmail.com",
    "password":"user1",
    "role":"USER",
    "profileImageUrl":""
}

###make user authenticate
POST https://atp-24eg112d06.onrender.com/auth/login
Content-Type: application/json

{
    "email":"user1@gmail.com",
    "password":"user1"
}

###logout the user
GET https://atp-24eg112d06.onrender.com/auth/logout

###read all articles
GET https://atp-24eg112d06.onrender.com/user-api/articles

### ADD comment by user to an article
PUT https://atp-24eg112d06.onrender.com/user-api/articles
Content-Type: application/json

{
    "articleId":"69b3bed9f2227eae7e6626ed",
    "comment":"This is my first comment"
}



###change password
PUT https://atp-24eg112d06.onrender.com/auth/password
Content-Type: application/json

{
    "currentPassword":"user1",
    "newPassword":"user1@"
}